#!/bin/bash

topdir=/gpfs/home/jhammond/spaghetty/python/archive

#for transpose in 4321 4312 4231 4213 4132 4123 ; do
#for transpose in 3421 3412 3241 3214 3142 3124 ; do
#for transpose in 2431 2413 2341 2314 2143 2134 ; do
#for transpose in 1423 1432 1342 1324 1243 1234 ; do
for transpose in 3421 ; do
    driver="transpose_${transpose}superflush_noflop.x"
    if [ -f "${topdir}/exe/${driver}" ]
    then
        rundir="${topdir}/flushruns/transpose_${transpose}superflush_noflop_`date +%d%b%Y_%Hh%Mm`"
        mkdir -p ${rundir}
        cd ${rundir}
        echo "submitting ${topdir}/exe/${driver}"
        qsub -n 1 -t 60 --mode smp "${topdir}/exe/${driver}"
    fi
done

